# Generated by Django 4.2.10 on 2024-03-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_easyuser_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyuser',
            name='email',
            field=models.CharField(default='sample@email.com', max_length=255),
            preserve_default=False,
        ),
    ]
